---
name: Objects-Collection
version: 0.34
author:
  - Zahatski Aliaksandr zag@cpan.org
abstract: Collections of data or objects.
license: perl
resources:
  license: http://dev.perl.org/licenses/
provides:
  Objects::Collection:
    file: lib/Objects/Collection.pm
    version: 0.34
  Objects::Collection::ActiveRecord:
    file: lib/Objects/Collection/ActiveRecord.pm
    version: 0.01
  Objects::Collection::AutoSQL:
    file: lib/Objects/Collection/AutoSQL.pm
    version: 0.02
  Objects::Collection::AutoSQLnotUnique:
    file: lib/Objects/Collection/AutoSQLnotUnique.pm
    version: 0.01
  Objects::Collection::Base:
    file: lib/Objects/Collection/Base.pm
    version: 0.01
  Objects::Collection::HashUnion:
    file: lib/Objects/Collection/HashUnion.pm
    version: 0.01
  Objects::Collection::Item:
    file: lib/Objects/Collection/Item.pm
    version: 0.02
  Objects::Collection::LazyObject:
    file: lib/Objects/Collection/LazyObject.pm
    version: 0.01
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
